# Generated by Django 3.1.6 on 2021-02-13 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0002_auto_20210210_2342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='Lesson',
            new_name='lesson',
        ),
    ]
